### ISSUE TITLE
Browsing Carousel?

### ISSUE THREAD

**Issue by mishushakov** [actions-on-google/assistant-conversation-nodejs#12]
hey, what happened to the Browsing Carousel response type?
can't find any examples

could you point me out?
thanks

**Comment by taycaldwell** [comment]
Browsing Carousel is named Browsing Collection for Actions Builder projects.

You can read more about Browsing Collection [here.](https://developers.google.com/assistant/conversational/prompts-selection#collection_browse)

**Comment by mishushakov** [comment]
when i try using it like in the example i get a TypeError

```
TypeError: CollectionBrowse is not a constructor
    at /Users/mish/Downloads/app-of-the-day/google/index.js:80:14
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Function.handler (/Users/mish/Downloads/app-of-the-day/node_modules/@assistant/conversation/dist/conversation/conversation.js:113:21)
    at async standard (/Users/mish/Downloads/app-of-the-day/node_modules/@assistant/conversation/dist/assistant.js:49:26)
```

**Comment by mishushakov** [comment]
Sorry, fixed by updating npm package
